/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 *
 * Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 * Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
 * Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

package problem45_hexagonalNums;

/**
 *
 * @author Novák Stanislav
 */
public class MainOld {

    public static void main(String[] args) {

        boolean stop = true;

        for(int i = 1; stop; i++) {
            if(i % 100000 == 0) {
                System.out.println("Trying number " + i);
            }

            if(isTriangle(i) && isPentagonal(i) && isHexagonal(i)) {
                System.out.println("New number: " + i);
                if(i > 40755) {
                    stop = false;
                    System.out.println("And the result is: " + i + "!!!");
                }
            }

        }

    }

    private static boolean isTriangle(int n) {

        int i = 1;
        int actNum = 2;

        while(i <= n) {

            if(i == n) {
                return true;
            }

            i += actNum;
            actNum++;
        }

        return false;
    }

    private static boolean isPentagonal(int n) {

        int i = 1;
        int actNum = 4;

        while(i <= n) {

            if(i == n) {
                return true;
            }

            i += actNum;
            actNum += 3;
        }

        return false;
    }

    private static boolean isHexagonal(int n) {

        int i = 1;
        int actNum = 5;

        while(i <= n) {

            if(i == n) {
                return true;
            }

            i += actNum;
            actNum += 4;
        }

        return false;
    }

}
