/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not
 * exceed four million.
 */

package problem02_fibonacci;

/**
 *
 * @author Novák Stanislav
 */
public class MainMoje {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        int x1 = 1;
        int x2 = 2;
        //System.out.println("New number: " + 2);

        int sum = 2;

        do {
            x2 = x1 + x2;
            x1 = x2 - x1;

            if(x2 % 2 == 0) {
                sum += x2;
                //System.out.println("New number: " + x2);
            }

        } while(x2 < 4000000);

        System.out.println("And the sum is: " + sum);

    }

}
